//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TopData.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom..
        /// </summary>
        internal static string _1004 {
            get {
                return ResourceManager.GetString("1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nee.
        /// </summary>
        internal static string _1005 {
            get {
                return ResourceManager.GetString("1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string _1006 {
            get {
                return ResourceManager.GetString("1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het database bestand is niet gevonden..
        /// </summary>
        internal static string _1100 {
            get {
                return ResourceManager.GetString("1100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze connectie komt reeds voor en is niet opgeslagen..
        /// </summary>
        internal static string _2000 {
            get {
                return ResourceManager.GetString("2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met het maken van een connectie....
        /// </summary>
        internal static string _2001 {
            get {
                return ResourceManager.GetString("2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het aanmaken van de connectie is mislukt..
        /// </summary>
        internal static string _2002 {
            get {
                return ResourceManager.GetString("2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanmaken connectie is geslaagd..
        /// </summary>
        internal static string _2003 {
            get {
                return ResourceManager.GetString("2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het muteren van de gegevens is mislukt..
        /// </summary>
        internal static string _2004 {
            get {
                return ResourceManager.GetString("2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De database connectie is gewijzigd..
        /// </summary>
        internal static string _2005 {
            get {
                return ResourceManager.GetString("2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De database connectie is verwijderd..
        /// </summary>
        internal static string _2006 {
            get {
                return ResourceManager.GetString("2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controleer de connectie gegevens..
        /// </summary>
        internal static string _2007 {
            get {
                return ResourceManager.GetString("2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectie is geslaagd..
        /// </summary>
        internal static string _2008 {
            get {
                return ResourceManager.GetString("2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Query&apos;s en de connecties worden opgehaald....
        /// </summary>
        internal static string _2009 {
            get {
                return ResourceManager.GetString("2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ophalen query&apos;s is gereed..
        /// </summary>
        internal static string _2010 {
            get {
                return ResourceManager.GetString("2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database = Geen verbinding.
        /// </summary>
        internal static string _2013 {
            get {
                return ResourceManager.GetString("2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string _2074 {
            get {
                return ResourceManager.GetString("2074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string _2074a {
            get {
                return ResourceManager.GetString("2074a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        internal static string _2075 {
            get {
                return ResourceManager.GetString("2075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe map.
        /// </summary>
        internal static string _2079 {
            get {
                return ResourceManager.GetString("2079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw SQL-Statement.
        /// </summary>
        internal static string _2080 {
            get {
                return ResourceManager.GetString("2080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een query kan alleen onder een map worden toegevoegd..
        /// </summary>
        internal static string _2081 {
            get {
                return ResourceManager.GetString("2081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raadplegen.
        /// </summary>
        internal static string _2082 {
            get {
                return ResourceManager.GetString("2082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzigen connectie gegevens....
        /// </summary>
        internal static string _2100 {
            get {
                return ResourceManager.GetString("2100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De connectiegegevens worden getest....
        /// </summary>
        internal static string _2101 {
            get {
                return ResourceManager.GetString("2101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het verwijderen van de connectie is mislukt..
        /// </summary>
        internal static string _2105 {
            get {
                return ResourceManager.GetString("2105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel bestanden (*.xlsx)|*.xlsx|Komma gescheiden bestanden (*.csv)|*.csv|Tekst bestanden (*.txt)|*.txt|Alle formaten (*.*)|*.*&quot;.
        /// </summary>
        internal static string _3000 {
            get {
                return ResourceManager.GetString("3000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef locatie en naam nieuw database bestand..
        /// </summary>
        internal static string _3001 {
            get {
                return ResourceManager.GetString("3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicatie database|*.db.
        /// </summary>
        internal static string _3002 {
            get {
                return ResourceManager.GetString("3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beheer Databaseconnectie(s).
        /// </summary>
        internal static string FrmmaintainDatabseConections {
            get {
                return ResourceManager.GetString("FrmmaintainDatabseConections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query beheer.
        /// </summary>
        internal static string FrmmaintainQueries {
            get {
                return ResourceManager.GetString("FrmmaintainQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standaard query tekst.
        /// </summary>
        internal static string FrmMaintainQueriesText {
            get {
                return ResourceManager.GetString("FrmMaintainQueriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string FrmUserLoginInText {
            get {
                return ResourceManager.GetString("FrmUserLoginInText", resourceCulture);
            }
        }
    }
}
